### ISSUE TITLE
[Note]: I have wrote an essay 

### ISSUE THREAD

**Issue by mobintmu** [me-dira/zarinpal-nestjs#16]
### Describe and write the question.

Thanks for your repository. I have wrote this article about this package.
https://blog.stackademic.com/integrating-zarinpal-payment-gateway-in-nestjs-12017908490d

**Comment by mehdi-ra** [comment]
Thank you very much dear @mobintmu 
Do you like to create a PR and add your essay to READEME.md as you like ?
